### ISSUE TITLE
请问一下，nacos-solon-cloud-plugin能自定义Metadata吗

### ISSUE THREAD

**Issue by guohuiyuan** [noear/solon-examples#1]

**Comment by noear** [comment]
这个不支持自定义。只能，通过 solon cloud 的 Instance::meta 接口进行中转。。。毕竟要考虑所有 的注册与发现服务的 统一适配（这样才能自由切换）。。。如果使用 soon 开发，一般不需要定制。

**Comment by noear** [comment]
现在能了，能过配置的形式。具体参考：

https://solon.noear.org/article/148
